# Reproducibility
seed: 42 # rng seed for torch, random and numpy
checkpoint: False # TODO: implement checkpoint resumation

# specify the default training parameters
defaults:
  - _self_
  - data: cifar10.yaml # dataset configuration
  - model: cifar10.yaml # architecture parameters

optimizer:
  _target_: torch.optim.Adam

loss:
  _target_: torch.nn.CrossEntropyLoss

trainer:
  _target_: src.loops.train_loop.create_engine