# Reproducibility
seed: 42
checkpoint: False

train:
  _target_: src.data.cifar_10_train_dataset.CIFAR10TrainDataset
  root: data
val:
  _target_: src.data.cifar_10_val_dataset.CIFAR10ValDataset
  root: data

model:
  _target_: src.models.cnn.CNN

params:
  epochs: 20
  batch_size: 32

optimizer:
  _target_: torch.optim.Adam

loss:
  _target_: torch.nn.CrossEntropyLoss

trainer:
  _target_: src.loops.train_loop.create_trainer